 
[[constraint]]
  name = "k8s.io/client-go"
  version = "v4.0.0"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "1fd2e63a9a370677308a42f24fd40c86438afddf"

[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.5"

[[override]]
  name = "github.com/sirupsen/logrus"
  revision = "07a84ee7412e7a28663d92930a1d46f81b124ee1"